// actionTypes.js
export const GET_TOTAL_ORDER_REQUEST = 'GET_TOTAL_ORDER_REQUEST';
export const GET_TOTAL_ORDER_SUCCESS = 'GET_TOTAL_ORDER_SUCCESS';
export const GET_TOTAL_ORDER_FAILURE = 'GET_TOTAL_ORDER_FAILURE';

export const GET_TOTAL_AMOUNT_REQUEST = 'GET_TOTAL_AMOUNT_REQUEST';
export const GET_TOTAL_AMOUNT_SUCCESS = 'GET_TOTAL_AMOUNT_SUCCESS';
export const GET_TOTAL_AMOUNT_FAILURE = 'GET_TOTAL_AMOUNT_FAILURE';

export const GET_TOTAL_SOLD_ITEMS_REQUEST = 'GET_TOTAL_SOLD_ITEMS_REQUEST';
export const GET_TOTAL_SOLD_ITEMS_SUCCESS = 'GET_TOTAL_SOLD_ITEMS_SUCCESS';
export const GET_TOTAL_SOLD_ITEMS_FAILURE = 'GET_TOTAL_SOLD_ITEMS_FAILURE';


export const GET_TOTAL_ORDER_AREA_REQUEST = 'GET_TOTAL_ORDER_AREA_REQUEST';
export const GET_TOTAL_ORDER_AREA_SUCCESS = 'GET_TOTAL_ORDER_AREA_SUCCESS';
export const GET_TOTAL_ORDER_AREA_FAILURE = 'GET_TOTAL_ORDER_AREA_FAILURE';

export const GET_TOTAL_AMOUNT_AREA_REQUEST = 'GET_TOTAL_AMOUNT_AREA_REQUEST';
export const GET_TOTAL_AMOUNT_AREA_SUCCESS = 'GET_TOTAL_AMOUNT_AREA_SUCCESS';
export const GET_TOTAL_AMOUNT_AREA_FAILURE = 'GET_TOTAL_AMOUNT_AREA_FAILURE';

export const GET_TOTAL_SOLD_AREA_ITEMS_REQUEST = 'GET_TOTAL_SOLD_AREA_ITEMS_REQUEST';
export const GET_TOTAL_SOLD_AREA_ITEMS_SUCCESS = 'GET_TOTAL_SOLD_AREA_ITEMS_SUCCESS';
export const GET_TOTAL_SOLD_AREA_ITEMS_FAILURE = 'GET_TOTAL_SOLD_AREA_ITEMS_FAILURE';
